name: chauffeur
description: ESCO VIP Chauffeur App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.9.1
  http: ^1.1.0
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
